config/routes.rb
Rails.application.routes.draw do
  devise_for :visitors
  devise_for :admins
  root to: 'home#index'
  #HomeController
  get 'rent', to: :rent, controller: 'home'
  get 'sale', to: :sale, controller: 'home'

  resources :properties, only: [:show]
  resources :visitors_properties, shallow: true
  #Users
  namespace :users do
    resources :properties
    resources :visitors_properties, only: [:show]

  end
  namespace :users do
    get 'dashboard', to: 'dashboard#index'
  end

  #Devise
  devise_for :users

  authenticate :admin do
   namespace :admins do
     get 'dashboard', to: 'dashboard#index'
     get 'properties', to: 'properties#index'

     resources :users do
       resources :properties, only: [:edit, :update, :destroy, :show]
     end
   end
 end

 mount ActionCable.server, at: '/cable'
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user
  has_many :pictures, dependent: :destroy

  has_many :visitors_properties, dependent: :destroy


  validates :title, :description, :price, :flag, :address, presence: true
end

app/controllers/admins/properties_controller.rb
class Admins::PropertiesController < Admins::BaseController

  def index
    @title = "Gerenciar Imóveis"
    @users_properties = Property.paginate(:page => params[:page], :per_page => 9)
  end

  def show
    @property = Property.find(params[:id])
    @pictures = @property.pictures

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @property }
    end
  end

  # GET /admins/properties/1/edit
  def edit
  end

  # PATCH/PUT /admins/properties/1
  def update
    if @users_property.update(users_property_params)
      redirect_to @users_property, notice: 'Property was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /admins/properties/1
  def destroy
    @property = Property.find(params[:id])
    @property.destroy

    redirect_to admins_properties_url, notice: 'Property was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_users_property
      @users_property = Property.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def users_property_params
      params.require(:property).permit(:title, :description, :address, :price, :flag, :image)
    end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

  # GET /users/properties/1
  def show
    @property = Property.find(params[:id])
    @pictures = @property.pictures

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @property }
    end
  end

end

app/controllers/users/properties_controller.rb
class Users::PropertiesController < Users::BaseController
  before_action :set_users_property, only: [:show, :edit, :update, :destroy]

  # GET /users/properties
  def index
    @properties = Property.where(user_id: current_user).paginate(:page => params[:page], :per_page => 12).order(updated_at: :desc)
    @title = "Gerenciar Imóveis"
  end

  # GET /users/properties/1
  def show
    @property  = Property.find(params[:id])
    @pictures = @property.pictures

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @property }
    end
  end

  # GET /users/properties/new
  def new
    @property = Property.new
    @title = "Cadastrar Imóvel"
  end

  # GET /users/properties/1/edit
  def edit
  end

  # POST /users/properties
  def create
    @property = Property.new(users_property_params)
    @property.user_id = current_user.id
    if @property.save

      if params[:images]
        params[:images].each { |image|
          @property.pictures.create(image: image)
        }
      end

      data = {property: "oi"}
      ActionCable.server.broadcast "propertynews", data
      redirect_to @property, notice: 'Property was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/properties/1
  def update
    if @property.update(users_property_params)

      if params[:images]
        params[:images].each { |image|
          @property.pictures.create(image: image)
        }
      end
      redirect_to @property, notice: 'Property was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/properties/1
  def destroy
    @property.destroy
    redirect_to users_properties_url, notice: 'Property was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_users_property
      @property = Property.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def users_property_params
      params.require(:property).permit(:title, :description, :address, :price, :flag, :images)
    end
end

app/helpers/users/properties_helper.rb
module Users::PropertiesHelper
end

app/views/admins/properties/_form.html.erb
<div class="container">
  <%= simple_form_for  [:admins, @property] , html: { multipart: true } do |f| %>
    <div class="col-12">
      <%= f.input :title %>
    </div>
    <div class="col-12">
      <%= f.input :description %>
    </div>
    <div class="col-12">
      <%= f.input :address %>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-4">
          <%= f.input :price %>
        </div>
        <div class="col-4">
          <%= f.input :flag, collection: ['Alugar', 'Vender'] %>
        </div>
        <!--<div class="col-4">
          <%= f.input :image, as: 'file' %>
        </div>-->

        <div class="col-4">
          <%= f.label :pictures, class: 'control-label' %>
          <div class="controls">
            <%= file_field_tag "images[]", type: :file, multiple: true %>
          </div>
        </div>

      </div>
    </div>
    <div class="row justify-content-md-center">
      <%= f.button :submit, class: 'btn btn-outline-success' %>
      <%= link_to 'Back', :back, class: 'btn btn-outline-secondary' %>
    </div>
  <% end %>
</div>

app/views/admins/properties/edit.html.erb
<div class="windows-popup">
  <h2 class="windows-popup-title"><%= @title %></h2>
		<%= render 'form' %>
  </div>
  </div>
</div>

app/views/admins/properties/index.html.erb
<section class="text-center">
<!-- Listagem de todos imóveis publicados para avaliação do administrador -->

<div class="card-group">
  <div class="row">
    <% @users_properties.each do |users_property| %>
    <div class="col-lg-4 public-card text-center">
      <div class="card">
        <% if users_property.pictures.empty? %>
          <%= image_tag('no-room.jpg', width: "300px", height: "200px", class: 'card-img-top' ) %>
        <% else %>
          <%= image_tag(users_property.pictures.first.image, width: "300px", height: "200px", class: 'card-img-top' ) %>
        <% end %>
        <div class="card-block">
          <h4 class="card-title"><%= users_property.title %></h4>
          <p class="card-text"><%= users_property.description %></p>
          <span> <%= users_property.address %> </span><br>
          <span> <%= users_property.flag %> </span><br>
          <span> <%= number_to_currency(users_property.price) %> </span><br>
          <%= link_to 'Visualizar', admins_user_property_path(user_id: users_property.user_id, id: users_property.id), class: 'btn btn-primary' %>
          <%= link_to 'Editar', edit_admins_user_property_path(user_id: users_property.user_id, id: users_property.id), class: 'btn btn-warning' %>
          <%= link_to 'Excluir', admins_user_property_path(user_id: users_property.user_id, id: users_property.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </div>
        <div class="card-footer">
          <!--<small class="text-muted">Last updated 3 mins ago</small>-->
          <small class="text-muted"><%= users_property.updated_at.strftime("Atualizado em %d/%m/%Y às %H:%M") %></small>
        </div>
      </div>
    </div>
    <% end %>
  </div><!-- /.row -->
</div>
<div class="public-card">
  <%= will_paginate(@users_properties, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'justify-content-center') %>
</div>
</section>

app/views/admins/properties/show.html.erb
<div class="windows-popup">
  <h2 class="windows-popup-title"><%= @property.title %></h2  >
  <div class="container">
    <div class="row">
      <div class="col-6">
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <% if @property.pictures.empty? %>
                <%= image_tag('no-room.jpg', width: "600px", height: "380px") %>
              <% else %>
                <%= image_tag(@property.pictures.first.image, width: "600px", height: "380px") %>
              <% end %>
            </div>

            <% @property.pictures.offset(1).each do |picture| %>
              <div class="carousel-item">
                <%= image_tag(picture.image, width: "600px", height: "380px") %>
              </div>
            <% end %>
          </div>
          <% unless @pictures.offset(1).empty? %>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          <% end %>
        </div>
      </div>
      <div class="col-6">

        <p>
          <strong>Descrição:</strong>
          <%= @property.description %>
        </p>

        <p>
          <strong>Preço:</strong>
          <%= number_to_currency(@property.price) %>
        </p>

        <p>
          <strong>Tipo:</strong>
          <%= @property.flag %>
        </p>

        <p>
          <strong>Endereço:</strong>
          <%= @property.address %>
        </p>

        <%= link_to 'Voltar', :back, class: 'btn btn-primary' %> |
        <%= link_to 'Editar', edit_admins_user_property_path(@property), class: 'btn btn-warning' %>
      </div>
    </div>
  </div>
</div>