config/routes.rb
Rails.application.routes.draw do
  devise_for :visitors
  devise_for :admins
  root to: 'home#index'
  #HomeController
  get 'rent', to: :rent, controller: 'home'
  get 'sale', to: :sale, controller: 'home'

  resources :properties, only: [:show]
  resources :visitors_properties, shallow: true
  #Users
  namespace :users do
    resources :properties
    resources :visitors_properties, only: [:show]

  end
  namespace :users do
    get 'dashboard', to: 'dashboard#index'
  end

  #Devise
  devise_for :users

  authenticate :admin do
   namespace :admins do
     get 'dashboard', to: 'dashboard#index'
     get 'properties', to: 'properties#index'

     resources :users do
       resources :properties, only: [:edit, :update, :destroy, :show]
     end
   end
 end

 mount ActionCable.server, at: '/cable'
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user
  has_many :pictures, dependent: :destroy

  has_many :visitors_properties, dependent: :destroy


  validates :title, :description, :price, :flag, :address, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :properties, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   validates :name, presence: true
end

app/models/users.rb
module Users
  def self.table_name_prefix
    'users_'
  end
end

app/controllers/admins/properties_controller.rb
class Admins::PropertiesController < Admins::BaseController

  def index
    @title = "Gerenciar Imóveis"
    @users_properties = Property.paginate(:page => params[:page], :per_page => 9)
  end

  def show
    @property = Property.find(params[:id])
    @pictures = @property.pictures

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @property }
    end
  end

  # GET /admins/properties/1/edit
  def edit
  end

  # PATCH/PUT /admins/properties/1
  def update
    if @users_property.update(users_property_params)
      redirect_to @users_property, notice: 'Property was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /admins/properties/1
  def destroy
    @property = Property.find(params[:id])
    @property.destroy

    redirect_to admins_properties_url, notice: 'Property was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_users_property
      @users_property = Property.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def users_property_params
      params.require(:property).permit(:title, :description, :address, :price, :flag, :image)
    end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < Admins::BaseController
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admins_dashboard_path, notice: 'Property was successfully destroyed.'
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

  # GET /users/properties/1
  def show
    @property = Property.find(params[:id])
    @pictures = @property.pictures

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @property }
    end
  end

end

app/controllers/users/base_controller.rb
class Users::BaseController < ApplicationController
  before_action :authenticate_user!
  layout 'users/layouts/application'
end

app/controllers/users/dashboard_controller.rb
class Users::DashboardController < Users::BaseController
  def index
    @properties = Property.where(user_id: current_user).paginate(:page => params[:page], :per_page => 12).order(updated_at: :desc)
  end
end

app/controllers/users/pictures_controller.rb
class Users::PicturesController < Users::BaseController
  # GET /pictures
  # GET /pictures.json
  def index

    @property = Property.find(params[:property_id])

    @pictures = @property.pictures

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pictures }
    end
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @picture = Picture.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/new
  # GET /pictures/new.json
  def new
    @property = Property.find(params[:property_id])
    @picture = @property.pictures.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/1/edit
  def edit
    #@property = Property.find(params[:property_id])

    @picture = Picture.find(params[:id])
    # @picture = Picture.find(params[:id])
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(params[:picture])

    if @picture.save
      respond_to do |format|
        format.html {
          render :json => [@picture.to_jq_upload].to_json,
          :content_type => 'text/html',
          :layout => false
        }
        format.json {
          render :json => [@picture.to_jq_upload].to_json
        }
      end
    else
      render :json => [{:error => "custom_failure"}], :status => 304
    end
  end

  # PUT /pictures/1
  # PUT /pictures/1.json
  def update

    @property = Property.find(params[:property_id])

    @picture = @property.pictures.find(params[:id])

    respond_to do |format|
      if @picture.update_attributes(picture_params)
        format.html { redirect_to gallery_path(@property), notice: 'Picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    #@property = Property.find(params[:property_id])
    #@picture = @property.pictures.find(params[:id])
    @picture = Picture.find(params[:id])
    @picture.destroy

    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  def make_default
    @picture = Picture.find(params[:id])
    @property = Property.find(params[:property_id])

    @property.cover = @picture.id
    @property.save

    respond_to do |format|
      format.js
    end
  end

  def first_picture
    @property = Property.find(params[:property_id])
    @pictures = @property.pictures.first
  end

  private

  def picture_params
    params.require(:picture).permit(:description, :property_id, :image)
  end
end

app/controllers/users/properties_controller.rb
class Users::PropertiesController < Users::BaseController
  before_action :set_users_property, only: [:show, :edit, :update, :destroy]

  # GET /users/properties
  def index
    @properties = Property.where(user_id: current_user).paginate(:page => params[:page], :per_page => 12).order(updated_at: :desc)
    @title = "Gerenciar Imóveis"
  end

  # GET /users/properties/1
  def show
    @property  = Property.find(params[:id])
    @pictures = @property.pictures

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @property }
    end
  end

  # GET /users/properties/new
  def new
    @property = Property.new
    @title = "Cadastrar Imóvel"
  end

  # GET /users/properties/1/edit
  def edit
  end

  # POST /users/properties
  def create
    @property = Property.new(users_property_params)
    @property.user_id = current_user.id
    if @property.save

      if params[:images]
        params[:images].each { |image|
          @property.pictures.create(image: image)
        }
      end

      data = {property: "oi"}
      ActionCable.server.broadcast "propertynews", data
      redirect_to @property, notice: 'Property was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/properties/1
  def update
    if @property.update(users_property_params)

      if params[:images]
        params[:images].each { |image|
          @property.pictures.create(image: image)
        }
      end
      redirect_to @property, notice: 'Property was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/properties/1
  def destroy
    @property.destroy
    redirect_to users_properties_url, notice: 'Property was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_users_property
      @property = Property.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def users_property_params
      params.require(:property).permit(:title, :description, :address, :price, :flag, :images)
    end
end

app/controllers/users/visitors_properties_controller.rb
class Users::VisitorsPropertiesController < Users::BaseController

  def show
    @title = "Lista de interessados"
    @visitors_property = VisitorsProperty.where(property_id: Property.select("id").where(user_id: current_user)).order(created_at: :desc).paginate(:page => params[:page], :per_page => 10)
  end

end

app/helpers/users/base_helper.rb
module Users::BaseHelper
end

app/helpers/users/dashboard_helper.rb
module Users::DashboardHelper
end

app/helpers/users/properties_helper.rb
module Users::PropertiesHelper
end

app/views/users/properties/_form.html.erb
<div class="container">
  <%= simple_form_for [:users, @property] , html: { multipart: true } do |f| %>
    <div class="col-12">
      <%= f.input :title %>
    </div>
    <div class="col-12">
      <%= f.input :description %>
    </div>
    <div class="col-12">
      <%= f.input :address %>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-4">
          <%= f.input :price %>
        </div>
        <div class="col-4">
          <%= f.input :flag, collection: ['Alugar', 'Vender'] %>
        </div>
        <!--<div class="col-4">
          <%= f.input :image, as: 'file' %>
        </div>-->

        <div class="col-4">
          <%= f.label :pictures, class: 'control-label' %>
          <div class="controls">
            <%= file_field_tag "images[]", type: :file, multiple: true %>
          </div>
        </div>

      </div>
    </div>
    <div class="row justify-content-md-center">
      <%= f.button :submit, class: 'btn btn-outline-success' %>
      <%= link_to 'Back', users_properties_path, class: 'btn btn-outline-secondary' %>
    </div>
  <% end %>
</div>

app/views/users/properties/index.html.erb
<div class="windows-popup">
  <h2 class="windows-popup-title"><%= @title %></h2>
  <table class="table">
    <thead class="thead-default">
      <tr>
        <th>Título</th>
        <th>Endereço</th>
        <th>Tipo</th>
        <th>Preço</th>
        <th colspan="3">Ações</th>
      </tr>
    </thead>

    <tbody>
      <% @properties.each do |users_property| %>
        <tr>
          <td><%= users_property.title %></td>
          <td><%= users_property.address %></td>
          <td><%= users_property.flag %></td>
          <td><%= number_to_currency(users_property.price) %></td>

          <td><%= link_to 'Visualizar', users_property_path(users_property), class: 'btn btn-info' %></td>
          <td><%= link_to 'Editar', edit_users_property_path(users_property), class: 'btn btn-warning'  %></td>
          <td><%= link_to 'Excluir', users_property_path(users_property), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate(@properties, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'justify-content-center') %>
</div>

app/views/users/properties/new.html.erb
<div class="windows-popup">
  <h2 class="windows-popup-title"><%= @title %></h2>
		<%= render 'form' %>
  </div>
  </div>
</div>

app/views/users/properties/show.html.erb
<div class="windows-popup">
  <h2 class="windows-popup-title"><%= @property.title %></h2  >
  <div class="container">
    <div class="row">
      <div class="col-6">
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <% if @property.pictures.empty? %>
                <%= image_tag('no-room.jpg', width: "600px", height: "380px") %>
              <% else %>
                <%= image_tag(@property.pictures.first.image, width: "600px", height: "380px") %>
              <% end %>
            </div>

            <% @property.pictures.offset(1).each do |picture| %>
              <div class="carousel-item">
                <%= image_tag(picture.image, width: "600px", height: "380px") %>
              </div>
            <% end %>
          </div>
          <% unless @pictures.offset(1).empty? %>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          <% end %>
        </div>
      </div>
      <div class="col-6">

        <p>
          <strong>Descrição:</strong>
          <%= @property.description %>
        </p>

        <p>
          <strong>Preço:</strong>
          <%= number_to_currency(@property.price) %>
        </p>

        <p>
          <strong>Tipo:</strong>
          <%= @property.flag %>
        </p>

        <p>
          <strong>Endereço:</strong>
          <%= @property.address %>
        </p>

        <%= link_to 'Voltar', :back, class: 'btn btn-primary' %> |
        <%= link_to 'Editar', edit_users_property_path(@property), class: 'btn btn-warning' %>
      </div>
    </div>
  </div>
</div>