config/routes.rb
Rails.application.routes.draw do
  devise_for :visitors
  devise_for :admins
  root to: 'home#index'
  #HomeController
  get 'rent', to: :rent, controller: 'home'
  get 'sale', to: :sale, controller: 'home'

  resources :properties, only: [:show]
  resources :visitors_properties, shallow: true
  #Users
  namespace :users do
    resources :properties
    resources :visitors_properties, only: [:show]

  end
  namespace :users do
    get 'dashboard', to: 'dashboard#index'
  end

  #Devise
  devise_for :users

  authenticate :admin do
   namespace :admins do
     get 'dashboard', to: 'dashboard#index'
     get 'properties', to: 'properties#index'

     resources :users do
       resources :properties, only: [:edit, :update, :destroy, :show]
     end
   end
 end

 mount ActionCable.server, at: '/cable'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :properties, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   validates :name, presence: true
end

app/models/users.rb
module Users
  def self.table_name_prefix
    'users_'
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < Admins::BaseController
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admins_dashboard_path, notice: 'Property was successfully destroyed.'
  end
end

app/controllers/users/base_controller.rb
class Users::BaseController < ApplicationController
  before_action :authenticate_user!
  layout 'users/layouts/application'
end

app/controllers/users/dashboard_controller.rb
class Users::DashboardController < Users::BaseController
  def index
    @properties = Property.where(user_id: current_user).paginate(:page => params[:page], :per_page => 12).order(updated_at: :desc)
  end
end

app/controllers/users/pictures_controller.rb
class Users::PicturesController < Users::BaseController
  # GET /pictures
  # GET /pictures.json
  def index

    @property = Property.find(params[:property_id])

    @pictures = @property.pictures

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pictures }
    end
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @picture = Picture.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/new
  # GET /pictures/new.json
  def new
    @property = Property.find(params[:property_id])
    @picture = @property.pictures.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/1/edit
  def edit
    #@property = Property.find(params[:property_id])

    @picture = Picture.find(params[:id])
    # @picture = Picture.find(params[:id])
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(params[:picture])

    if @picture.save
      respond_to do |format|
        format.html {
          render :json => [@picture.to_jq_upload].to_json,
          :content_type => 'text/html',
          :layout => false
        }
        format.json {
          render :json => [@picture.to_jq_upload].to_json
        }
      end
    else
      render :json => [{:error => "custom_failure"}], :status => 304
    end
  end

  # PUT /pictures/1
  # PUT /pictures/1.json
  def update

    @property = Property.find(params[:property_id])

    @picture = @property.pictures.find(params[:id])

    respond_to do |format|
      if @picture.update_attributes(picture_params)
        format.html { redirect_to gallery_path(@property), notice: 'Picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    #@property = Property.find(params[:property_id])
    #@picture = @property.pictures.find(params[:id])
    @picture = Picture.find(params[:id])
    @picture.destroy

    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  def make_default
    @picture = Picture.find(params[:id])
    @property = Property.find(params[:property_id])

    @property.cover = @picture.id
    @property.save

    respond_to do |format|
      format.js
    end
  end

  def first_picture
    @property = Property.find(params[:property_id])
    @pictures = @property.pictures.first
  end

  private

  def picture_params
    params.require(:picture).permit(:description, :property_id, :image)
  end
end

app/controllers/users/properties_controller.rb
class Users::PropertiesController < Users::BaseController
  before_action :set_users_property, only: [:show, :edit, :update, :destroy]

  # GET /users/properties
  def index
    @properties = Property.where(user_id: current_user).paginate(:page => params[:page], :per_page => 12).order(updated_at: :desc)
    @title = "Gerenciar Imóveis"
  end

  # GET /users/properties/1
  def show
    @property  = Property.find(params[:id])
    @pictures = @property.pictures

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @property }
    end
  end

  # GET /users/properties/new
  def new
    @property = Property.new
    @title = "Cadastrar Imóvel"
  end

  # GET /users/properties/1/edit
  def edit
  end

  # POST /users/properties
  def create
    @property = Property.new(users_property_params)
    @property.user_id = current_user.id
    if @property.save

      if params[:images]
        params[:images].each { |image|
          @property.pictures.create(image: image)
        }
      end

      data = {property: "oi"}
      ActionCable.server.broadcast "propertynews", data
      redirect_to @property, notice: 'Property was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/properties/1
  def update
    if @property.update(users_property_params)

      if params[:images]
        params[:images].each { |image|
          @property.pictures.create(image: image)
        }
      end
      redirect_to @property, notice: 'Property was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/properties/1
  def destroy
    @property.destroy
    redirect_to users_properties_url, notice: 'Property was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_users_property
      @property = Property.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def users_property_params
      params.require(:property).permit(:title, :description, :address, :price, :flag, :images)
    end
end

app/controllers/users/visitors_properties_controller.rb
class Users::VisitorsPropertiesController < Users::BaseController

  def show
    @title = "Lista de interessados"
    @visitors_property = VisitorsProperty.where(property_id: Property.select("id").where(user_id: current_user)).order(created_at: :desc).paginate(:page => params[:page], :per_page => 10)
  end

end

app/helpers/users/base_helper.rb
module Users::BaseHelper
end

app/helpers/users/dashboard_helper.rb
module Users::DashboardHelper
end

app/helpers/users/properties_helper.rb
module Users::PropertiesHelper
end

app/views/users/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-info">

  <%= link_to 'Gerenciar Imóveis', root_path, class: 'navbar-brand' %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav" >
      <li class="nav-item">
        <%= link_to 'Dashboard', users_dashboard_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Cadastrar', new_users_property_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Gerenciar', users_properties_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Interessados', users_visitors_property_path(current_user), class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Perfil</a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.name %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to 'Sair', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
            </div>
          </li>
       <% else %>
         <li class="nav-item">
            <%= link_to 'Entrar', new_user_session_path, class: 'nav-link' %>
         </li>
       <% end %>
    </ul>
  </div>
</nav>

app/views/users/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title><%= @title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'users/application', media: 'all',
      'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'users/application', 'data-turbolinks-track': 'reload' %>

    <%= render 'users/layouts/shim' %>
  </head>
  <body>

    <%= render 'users/layouts/navbar' %>
    <%= render 'shared/flash_messages'%>

    <div class="container">
      <%= yield %>
    </div>

    <%= render 'users/layouts/footer' %>
  </body>
</html>