config/routes.rb
Rails.application.routes.draw do
  devise_for :visitors
  devise_for :admins
  root to: 'home#index'
  #HomeController
  get 'rent', to: :rent, controller: 'home'
  get 'sale', to: :sale, controller: 'home'

  resources :properties, only: [:show]
  resources :visitors_properties, shallow: true
  #Users
  namespace :users do
    resources :properties
    resources :visitors_properties, only: [:show]

  end
  namespace :users do
    get 'dashboard', to: 'dashboard#index'
  end

  #Devise
  devise_for :users

  authenticate :admin do
   namespace :admins do
     get 'dashboard', to: 'dashboard#index'
     get 'properties', to: 'properties#index'

     resources :users do
       resources :properties, only: [:edit, :update, :destroy, :show]
     end
   end
 end

 mount ActionCable.server, at: '/cable'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  def name
    'Administrador'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  include Paperclip::Glue
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :property

  has_attached_file :image,
  :path => ":rails_root/public/images/:id/:filename",
  :url  => "/images/:id/:filename"

  do_not_validate_attachment_file_type :image
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user
  has_many :pictures, dependent: :destroy

  has_many :visitors_properties, dependent: :destroy


  validates :title, :description, :price, :flag, :address, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :properties, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   validates :name, presence: true
end

app/models/users.rb
module Users
  def self.table_name_prefix
    'users_'
  end
end

app/models/visitor.rb
class Visitor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :visitors_properties, dependent: :destroy

  validates :name, presence: true

  def self.search(query)
    order(:name).where("name ilike ?", "%#{params[:query]}%")
  end
end

app/models/visitors_property.rb
class VisitorsProperty < ApplicationRecord
  belongs_to :property
  belongs_to :visitor
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  layout :layout_by_resource

  protected
  def layout_by_resource
    if devise_controller?
      if resource_name == :user && ['edit', 'update'].include?(action_name)
        "users/layouts/application"
      elsif resource_name == :admin && not(['new', 'create'].include?(action_name))
        "admins/layouts/application"
      elsif resource_name == :visitor && ['edit', 'update'].include?(action_name)
        "layouts/application"
      else
        "layouts/login"
      end
    else
      "layouts/application"
    end
  end

  def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
     devise_parameter_sanitizer.permit(:account_update, keys: [:name])
   end

  def after_sign_in_path_for(resource)
    if resource.is_a? Admin
      admins_dashboard_path
    elsif resource.is_a? User
      users_dashboard_path
    elsif resource.is_a? Visitor
      root_path
    else
      root_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @title = "Gerenciar Imóveis"
    @properties = Property.paginate(:page => params[:page], :per_page => 12).order(updated_at: :desc)

    #@visitor_property = VisitorsProperty.where(property_id: @properties.ids).count

  end

  def rent
    @title = "Gerenciar Imóveis - Locação"
  	@users_properties = Property.where(flag: "Alugar").paginate(:page => params[:page], :per_page => 12).order(updated_at: :desc)
  end

  def sale
    @title = "Gerenciar Imóveis - Venda"
  	@users_properties = Property.where(flag: "Vender").paginate(:page => params[:page], :per_page => 12).order(updated_at: :desc)
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  # GET /pictures
  # GET /pictures.json
  def index

    @property = Property.find(params[:property_id])

    @pictures = @property.pictures

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pictures }
    end
  end

  def show
    @picture = Picture.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @picture }
    end
  end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

  # GET /users/properties/1
  def show
    @property = Property.find(params[:id])
    @pictures = @property.pictures

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @property }
    end
  end

end

app/controllers/users/base_controller.rb
class Users::BaseController < ApplicationController
  before_action :authenticate_user!
  layout 'users/layouts/application'
end

app/controllers/visitors_properties_controller.rb
class VisitorsPropertiesController < ApplicationController
  before_action :authenticate_visitor!
  layout 'users/layouts/application'

  # GET /users/properties/new
  def new
    @visitor_property = VisitorsProperty.new
  end

  # POST /users/properties
  def create
    @visitor_property = VisitorsProperty.new
    @visitor_property.property_id = params[:property_id]
    @visitor_property.visitor_id = current_visitor.id
    @visitor = Visitor.find(current_visitor.id)
    @user = User.where(id: Property.select("user_id").where(id: @visitor_property.property_id)).first
    @property = Property.where(id: @visitor_property.property_id).first

    if @visitor_property.save
      redirect_to property_path(@visitor_property.property_id), notice: 'Marcado interesse com sucesso.'

      data = { count: VisitorsProperty.where(property_id: @visitor_property.property_id).count, id: @visitor_property.property_id}
      #data = data = VisitorsProperty.where(property_id: @visitor_property.property_id).count
      ActionCable.server.broadcast "propertynews", data

      UserMailer.user_email(@visitor, @user, @property).deliver_later
      UserMailer.visitor_email(@visitor, @property).deliver_later

    else
      render root_path, notice: 'Algo deu errado, por favor entre em contato com o administrador!'
    end
  end

  def visitor_property_params
    params.require(:visitors_properties).permit(:property_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    { success: 'alert-success', error: 'alert-danger', alert: 'alert-warning',
      notice: 'alert-info' }[flash_type.to_sym] || flash_type.to_s
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users/base_helper.rb
module Users::BaseHelper
end

app/helpers/users/dashboard_helper.rb
module Users::DashboardHelper
end

app/helpers/users/properties_helper.rb
module Users::PropertiesHelper
end

app/helpers/visitors_properties_helper.rb
module VisitorsPropertiesHelper
end

app/views/admins/layouts/_footer.html.erb
<footer class="text-muted">
  <div class="container">
  </br>
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
  </br>
    <div class="container text-center">
      <span class="text-muted">Desenvolvido por Filipe Kuhn & Rogério Miss - Copyright 2017 ©</span>
    </div>
  </div>
</footer>

app/views/admins/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-info">

  <%= link_to 'Gerenciar Imóveis', root_path, class: 'navbar-brand' %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <ul class="navbar-nav ml-auto" >
    <li class="nav-item">
      <%= link_to 'Dashboard', admins_dashboard_path, class: 'nav-link' %>
    </li>
  </ul>
  <ul class="navbar-nav ml-auto" >
    <li class="nav-item">
      <%= link_to 'Publicações', admins_properties_path, class: 'nav-link' %>
    </li>
  </ul>
  <ul class="navbar-nav ml-auto">
    <li class="nav-item">
      <a class="nav-link" href="#">Mensagens</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Perfil</a>
    </li>
  </ul>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <% if admin_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_admin.name %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to 'Sair', destroy_admin_session_path, method: :delete, class: 'dropdown-item' %>
            </div>
          </li>
       <% else %>
         <li class="nav-item">
            <%= link_to 'Entrar', new_admin_session_path, class: 'nav-link' %>
         </li>
       <% end %>
    </ul>
  </div>
</nav>

app/views/admins/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/admins/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Área administrativa</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'admins/application', media: 'all',
      'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admins/application', 'data-turbolinks-track': 'reload' %>

    <%= render 'admins/layouts/shim' %>

  </head>
  <body>

    <%= render 'admins/layouts/navbar' %>
    <%= render 'shared/flash_messages' %>

    <div class="container">    
      <%= yield %>
    </div>

  </body>
</html>

app/views/layouts/_footer.html.erb
<footer class="footer bg-light">
	<div class="container">
	</br>
		<p class="float-right">
			<a href="#">Back to top</a>
		</p>
	</div>
	</br>
	<div class="container text-center">
		<span class="text-muted">Desenvolvido por Filipe Kuhn & Rogério Miss - Copyright 2017 ©</span>
	</div>
</footer>

app/views/layouts/_footer2.html.erb
<!----------- Footer ------------>
    <footer class="footer-bs">
        <div class="row">
        	<div class="col-md-3 footer-brand animated fadeInLeft">
            	<h2>Logo</h2>
                <p>Suspendisse hendrerit tellus laoreet luctus pharetra. Aliquam porttitor vitae orci nec ultricies. Curabitur vehicula, libero eget faucibus faucibus, purus erat eleifend enim, porta pellentesque ex mi ut sem.</p>
                <p>© 2014 BS3 UI Kit, All rights reserved</p>
            </div>
        	<div class="col-md-4 footer-nav animated fadeInUp">
            	<h4>Menu —</h4>
            	<div class="col-md-6">
                    <ul class="pages">
                        <li><a href="#">Travel</a></li>
                        <li><a href="#">Nature</a></li>
                        <li><a href="#">Explores</a></li>
                        <li><a href="#">Science</a></li>
                        <li><a href="#">Advice</a></li>
                    </ul>
                </div>
            	<div class="col-md-6">
                    <ul class="list">
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Contacts</a></li>
                        <li><a href="#">Terms & Condition</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                    </ul>
                </div>
            </div>
        	<div class="col-md-2 footer-social animated fadeInDown">
            	<h4>Follow Us</h4>
            	<ul>
                	<li><a href="#">Facebook</a></li>
                	<li><a href="#">Twitter</a></li>
                	<li><a href="#">Instagram</a></li>
                	<li><a href="#">RSS</a></li>
                </ul>
            </div>
        	<div class="col-md-3 footer-ns animated fadeInRight">
            	<h4>Newsletter</h4>
                <p>A rover wearing a fuzzy suit doesn’t alarm the real penguins</p>
                <p>
                    <div class="input-group">
                      <input type="text" class="form-control" placeholder="Search for...">
                      <span class="input-group-btn">
                        <button class="btn btn-default" type="button"><span class="glyphicon glyphicon-envelope"></span></button>
                      </span>
                    </div><!-- /input-group -->
                 </p>
            </div>
        </div>
    </footer>

app/views/layouts/_imagebar.html.erb
<div class="parallax">
  
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">

  <%= link_to 'Gerenciar Imóveis', root_path, class: 'navbar-brand' %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav" >
      <li class="nav-item ">
        <%= link_to 'Alugar', rent_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Venda', sale_path, class: 'nav-link' %>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.name %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to 'Sair', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
            <%= link_to 'Dashboard', users_dashboard_path, class: 'dropdown-item' %>
          </div>
        </li>
      <% elsif visitor_signed_in? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= current_visitor.name %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to 'Sair', destroy_visitor_session_path, method: :delete, class: 'dropdown-item' %>
        </div>
      </li>
      <% elsif admin_signed_in? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= current_admin.name %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to 'Sair', destroy_admin_session_path, method: :delete, class: 'dropdown-item' %>
          <%= link_to 'Dashboard', admins_dashboard_path, class: 'dropdown-item' %>
        </div>
      </li>
      <% else %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Entrar
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to 'Visitante', new_visitor_session_path,  class: 'dropdown-item' %>
            <%= link_to 'Usuário', new_user_session_path,  class: 'dropdown-item' %>
            <%= link_to 'Administrador', new_admin_session_path,  class: 'dropdown-item' %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title><%= @title %></title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'users/application', media: 'all',
      'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= render 'layouts/shim' %>
  </head>
  <body>

    <%= render 'layouts/navbar' %>
    <%= render 'layouts/imagebar' %>
    <%= render 'shared/flash_messages'%>

    <div class="container">
      <%= yield %>
    </div>

    <%= render 'users/layouts/footer' %>

  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Login</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
      'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= render 'layouts/shim' %>
  </head>
  <body class="auth-login">
    <%= render 'shared/flash_messages'%>

    <div class="container-fluid">
      <%= yield %>
    </div>



  </body>
</html>

app/views/layouts/session.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Session</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'session', media: 'all',
      'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'session', 'data-turbolinks-track': 'reload' %>

    <%= render 'layouts/shim' %>

  </head>
  <body>

		<div id="<%= controller_name %>-<%= action_name %>" class="container">
			<div class="vertical-centering horizontal-centering">
				<%= render 'shared/flash_messages' %>

				<div>
					<h3 class="text-center gray-text2"><%= yield :title %></h3>
					<p class="gray-text2"><%= yield :sub_title %></p>
				</div>

				<%= yield %>

			</div> <!-- .vertical-centering .horizontal-centering -->
		</div> <!-- #home-index -->

  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> alert-dismissible fade show" role="alert">
    <button class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= message %>
  </div>
<% end %>